project:
  type: website
  # output-dir: _site

website:
  title: "Jander Moreira"
  description: "Informções gerais sobre mim"
  image: escritorio.png
  site-url: "https://jandermoreira.github.io"
  navbar: true
    # left:
    #   - href: index.qmd
    #     text: "![](house.png){width=16}"
  search: false
  


format:
  html:
    lang: "pt-BR"
    theme: simplex
    css: styles.css
    toc: true
